### ISSUE TITLE
The website doesn't load

### ISSUE THREAD

**Issue by Valleriite** [LambdAurora/aurbrowser#18]
**Describe the bug**
The website doesn't seem to load,the browser shows the error "We can’t connect to the server at aurbrowser.tk."
I guess the domain expired but I am not sure

**To Reproduce**
1. Go to the address bat
2. Type "aurbrowser.tk"(without the quotes)
3. Press enter

**Expected behavior**
The website loads.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser: Firefox
 - Branch: I guess master,not sure,I am using the normal website(aurbrowser.tk)

**Comment by LambdAurora** [comment]
Domain name is no more, there is https://aurbrowser.netlify.app/home but still, the whole thing with CORS-everywhere does not work anymore.

**Comment by Valleriite** [comment]
Thank you!
