### ISSUE TITLE
Browser freeze after the result of a big search

### ISSUE THREAD

**Issue by adri326** [LambdAurora/aurbrowser#2]
Running a search which returns a lot of packages (say `python2` by name & description), once the search is being made, the load made on the browser to parse & convert the result to actual elements blocks it for a few seconds up to a few minutes.

**Comment by unixfox** [comment]
That's strange because I don't have this kind of issue on Firefox nor on Chrome/Chromium. Is your computer old?

**Comment by adri326** [comment]
a9c8d3cfaca27f0f628c452310c0b3b3fb92ae1e

**Comment by unixfox** [comment]
So I think you can close this issue then.
